name: 'workflow_run status'
description: 'Associate workflow_run status with the base commit of workflow_run triggered event'
author: 'haya14busa'
inputs:
  job_id:
    description: 'job_id'
    default: '${{ github.context.job }}'
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  requested_as_pending:
    description: 'handle requested action type as pending'
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
